/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param user The user account ID of the user to add.
 * @param group The name of the group to add.
 */

data class ActorsMap (
    /* The user account ID of the user to add. */
    @Json(name = "user")
    val user: kotlin.Array<kotlin.String>? = null,
    /* The name of the group to add. */
    @Json(name = "group")
    val group: kotlin.Array<kotlin.String>? = null
) 



