/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.User

import com.squareup.moshi.Json
/**
 * Metadata for an issue attachment.
 * @param id The ID of the attachment.
 * @param self The URL of the attachment metadata details.
 * @param filename The name of the attachment file.
 * @param author Details of the user who attached the file.
 * @param created The datetime the attachment was created.
 * @param size The size of the attachment.
 * @param mimeType The MIME type of the attachment.
 * @param properties Additional properties of the attachment.
 * @param content The URL of the attachment.
 * @param thumbnail The URL of a thumbnail representing the attachment.
 */

data class AttachmentMetadata (
    /* The ID of the attachment. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The URL of the attachment metadata details. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* The name of the attachment file. */
    @Json(name = "filename")
    val filename: kotlin.String? = null,
    /* Details of the user who attached the file. */
    @Json(name = "author")
    val author: User? = null,
    /* The datetime the attachment was created. */
    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,
    /* The size of the attachment. */
    @Json(name = "size")
    val size: kotlin.Long? = null,
    /* The MIME type of the attachment. */
    @Json(name = "mimeType")
    val mimeType: kotlin.String? = null,
    /* Additional properties of the attachment. */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    /* The URL of the attachment. */
    @Json(name = "content")
    val content: kotlin.String? = null,
    /* The URL of a thumbnail representing the attachment. */
    @Json(name = "thumbnail")
    val thumbnail: kotlin.String? = null
) 



