/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AuditRecordBean

import com.squareup.moshi.Json
/**
 * Container for a list of audit records.
 * @param offset The number of audit items skipped before the first item in this list.
 * @param limit The requested or default limit on the number of audit items to be returned.
 * @param total The total number of audit items returned.
 * @param records The list of audit items.
 */

data class AuditRecords (
    /* The number of audit items skipped before the first item in this list. */
    @Json(name = "offset")
    val offset: kotlin.Int? = null,
    /* The requested or default limit on the number of audit items to be returned. */
    @Json(name = "limit")
    val limit: kotlin.Int? = null,
    /* The total number of audit items returned. */
    @Json(name = "total")
    val total: kotlin.Long? = null,
    /* The list of audit items. */
    @Json(name = "records")
    val records: kotlin.Array<AuditRecordBean>? = null
) 



