/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * A field auto-complete suggestion.
 * @param value The value of a suggested item.
 * @param displayName The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
 */

data class AutoCompleteSuggestion (
    /* The value of a suggested item. */
    @Json(name = "value")
    val value: kotlin.String? = null,
    /* The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag. */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null
) 



