/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of an issue navigator column item.
 * @param label The issue navigator column label.
 * @param value The issue navigator column value.
 */

data class ColumnItem (
    /* The issue navigator column label. */
    @Json(name = "label")
    val label: kotlin.String? = null,
    /* The issue navigator column value. */
    @Json(name = "value")
    val value: kotlin.String? = null
) 



