/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EntityProperty
import org.openapitools.client.models.UserDetails
import org.openapitools.client.models.Visibility

import com.squareup.moshi.Json
/**
 * A comment.
 * @param self The URL of the comment.
 * @param id The ID of the comment.
 * @param author The ID of the user who created the comment.
 * @param body The comment text in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/).
 * @param renderedBody The rendered version of the comment.
 * @param updateAuthor The ID of the user who updated the comment last.
 * @param created The date and time at which the comment was created.
 * @param updated The date and time at which the comment was updated last.
 * @param visibility The group or role to which this comment is visible. Optional on create and update.
 * @param jsdPublic Whether the comment is visible in Jira Service Desk. Defaults to true when comments are created in the Jira Cloud Platform. This includes when the site doesn't use Jira Service Desk or the project isn't a Jira Service Desk project and, therefore, there is no Jira Service Desk for the issue to be visible on. To create a comment with its visibility in Jira Service Desk set to false, use the Jira Service Desk REST API [Create request comment](https://developer.atlassian.com/cloud/jira/service-desk/rest/#api-rest-servicedeskapi-request-issueIdOrKey-comment-post) operation.
 * @param properties A list of comment properties. Optional on create and update.
 */

data class Comment (
    /* The URL of the comment. */
    @Json(name = "self")
    val self: kotlin.String? = null,
    /* The ID of the comment. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The ID of the user who created the comment. */
    @Json(name = "author")
    val author: UserDetails? = null,
    /* The comment text in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/). */
    @Json(name = "body")
    val body: kotlin.Any? = null,
    /* The rendered version of the comment. */
    @Json(name = "renderedBody")
    val renderedBody: kotlin.String? = null,
    /* The ID of the user who updated the comment last. */
    @Json(name = "updateAuthor")
    val updateAuthor: UserDetails? = null,
    /* The date and time at which the comment was created. */
    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,
    /* The date and time at which the comment was updated last. */
    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null,
    /* The group or role to which this comment is visible. Optional on create and update. */
    @Json(name = "visibility")
    val visibility: Visibility? = null,
    /* Whether the comment is visible in Jira Service Desk. Defaults to true when comments are created in the Jira Cloud Platform. This includes when the site doesn't use Jira Service Desk or the project isn't a Jira Service Desk project and, therefore, there is no Jira Service Desk for the issue to be visible on. To create a comment with its visibility in Jira Service Desk set to false, use the Jira Service Desk REST API [Create request comment](https://developer.atlassian.com/cloud/jira/service-desk/rest/#api-rest-servicedeskapi-request-issueIdOrKey-comment-post) operation. */
    @Json(name = "jsdPublic")
    val jsdPublic: kotlin.Boolean? = null,
    /* A list of comment properties. Optional on create and update. */
    @Json(name = "properties")
    val properties: kotlin.Array<EntityProperty>? = null
) 



