/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Count of issues assigned to a component.
 * @param self The URL for this count of issues for a component.
 * @param issueCount The count of issues assigned to a component.
 */

data class ComponentIssuesCount (
    /* The URL for this count of issues for a component. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* The count of issues assigned to a component. */
    @Json(name = "issueCount")
    val issueCount: kotlin.Long? = null
) 



