/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.JQLQueryWithUnknownUsers

import com.squareup.moshi.Json
/**
 * The converted JQL queries.
 * @param queryStrings The list of converted query strings with account IDs in place of user identifiers.
 * @param queriesWithUnknownUsers List of queries containing user information that could not be mapped to an existing user
 */

data class ConvertedJQLQueries (
    /* The list of converted query strings with account IDs in place of user identifiers. */
    @Json(name = "queryStrings")
    val queryStrings: kotlin.Array<kotlin.String>? = null,
    /* List of queries containing user information that could not be mapped to an existing user */
    @Json(name = "queriesWithUnknownUsers")
    val queriesWithUnknownUsers: kotlin.Array<JQLQueryWithUnknownUsers>? = null
) 



