/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details about the default workflow.
 * @param workflow The name of the workflow to set as the default workflow.
 * @param updateDraftIfNeeded Whether a draft workflow scheme is created or updated when updating an active workflow scheme. The draft is updated with the new default workflow. Defaults to `false`.
 */

data class DefaultWorkflow (
    /* The name of the workflow to set as the default workflow. */
    @Json(name = "workflow")
    val workflow: kotlin.String,
    /* Whether a draft workflow scheme is created or updated when updating an active workflow scheme. The draft is updated with the new default workflow. Defaults to `false`. */
    @Json(name = "updateDraftIfNeeded")
    val updateDraftIfNeeded: kotlin.Boolean? = null
) 



