/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.FailedWebhook

import com.squareup.moshi.Json
/**
 * A page of failed webhooks.
 * @param values The list of webhooks.
 * @param maxResults The maximum number of items on the page. If the list of values is shorter than this number, then there are no more pages.
 * @param next The URL to the next page of results. Present only if the request returned at least one result.The next page may be empty at the time of receiving the response, but new failed webhooks may appear in time. You can save the URL to the next page and query for new results periodically (for example, every hour).
 */

data class FailedWebhooks (
    /* The list of webhooks. */
    @Json(name = "values")
    val values: kotlin.Array<FailedWebhook>,
    /* The maximum number of items on the page. If the list of values is shorter than this number, then there are no more pages. */
    @Json(name = "maxResults")
    val maxResults: kotlin.Int,
    /* The URL to the next page of results. Present only if the request returned at least one result.The next page may be empty at the time of receiving the response, but new failed webhooks may appear in time. You can save the URL to the next page and query for new results periodically (for example, every hour). */
    @Json(name = "next")
    val next: java.net.URI? = null
) 



