/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.JqlQueryClauseOperand
import org.openapitools.client.models.JqlQueryField

import com.squareup.moshi.Json
/**
 * A clause that asserts the current value of a field. For example, `summary ~ test`.
 * @param field 
 * @param operator The operator between the field and operand.
 * @param operand 
 */

data class FieldValueClause (
    @Json(name = "field")
    val field: JqlQueryField,
    /* The operator between the field and operand. */
    @Json(name = "operator")
    val operator: FieldValueClause.Operator,
    @Json(name = "operand")
    val operand: JqlQueryClauseOperand
) 


{
    /**
    * The operator between the field and operand.
    * Values: equal,exclamationEqual,greaterThan,lessThan,greaterThanEqual,lessThanOrEqualTo,`in`,notIn,tildeEqual,`is`,isNot
    */
    
    enum class Operator(val value: kotlin.String){
        @Json(name = "=") equal("="),
        @Json(name = "!=") exclamationEqual("!="),
        @Json(name = ">") greaterThan(">"),
        @Json(name = "<") lessThan("<"),
        @Json(name = ">=") greaterThanEqual(">="),
        @Json(name = "<=") lessThanOrEqualTo("<="),
        @Json(name = "in") `in`("in"),
        @Json(name = "not in") notIn("not in"),
        @Json(name = "~=") tildeEqual("~="),
        @Json(name = "is") `is`("is"),
        @Json(name = "is not") isNot("is not");
    }
}

