/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of a field that can be used in advanced searches.
 * @param value The field identifier.
 * @param displayName The display name of the field.
 * @param orderable Whether the field can be used in a query's `ORDER BY` clause.
 * @param searchable Whether the content of this field can be searched.
 * @param auto Whether the field provide auto-complete suggestions.
 * @param cfid If the item is a custom field, the ID of the custom field.
 * @param operators The valid search operators for the field.
 * @param types The data types of items in the field.
 */

data class FieldReferenceData (
    /* The field identifier. */
    @Json(name = "value")
    val value: kotlin.String? = null,
    /* The display name of the field. */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,
    /* Whether the field can be used in a query's `ORDER BY` clause. */
    @Json(name = "orderable")
    val orderable: FieldReferenceData.Orderable? = null,
    /* Whether the content of this field can be searched. */
    @Json(name = "searchable")
    val searchable: FieldReferenceData.Searchable? = null,
    /* Whether the field provide auto-complete suggestions. */
    @Json(name = "auto")
    val auto: FieldReferenceData.Auto? = null,
    /* If the item is a custom field, the ID of the custom field. */
    @Json(name = "cfid")
    val cfid: kotlin.String? = null,
    /* The valid search operators for the field. */
    @Json(name = "operators")
    val operators: kotlin.Array<kotlin.String>? = null,
    /* The data types of items in the field. */
    @Json(name = "types")
    val types: kotlin.Array<kotlin.String>? = null
) 


{
    /**
    * Whether the field can be used in a query's `ORDER BY` clause.
    * Values: `true`,`false`
    */
    
    enum class Orderable(val value: kotlin.String){
        @Json(name = "true") `true`("true"),
        @Json(name = "false") `false`("false");
    }
    /**
    * Whether the content of this field can be searched.
    * Values: `true`,`false`
    */
    
    enum class Searchable(val value: kotlin.String){
        @Json(name = "true") `true`("true"),
        @Json(name = "false") `false`("false");
    }
    /**
    * Whether the field provide auto-complete suggestions.
    * Values: `true`,`false`
    */
    
    enum class Auto(val value: kotlin.String){
        @Json(name = "true") `true`("true"),
        @Json(name = "false") `false`("false");
    }
}

