/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * The field configuration for an issue type.
 * @param fieldConfigurationSchemeId The ID of the field configuration scheme.
 * @param issueTypeId The ID of the issue type or *default*. When set to *default* this field configuration issue type item applies to all issue types without a field configuration.
 * @param fieldConfigurationId The ID of the field configuration.
 */

data class FieldConfigurationIssueTypeItem (
    /* The ID of the field configuration scheme. */
    @Json(name = "fieldConfigurationSchemeId")
    val fieldConfigurationSchemeId: kotlin.String,
    /* The ID of the issue type or *default*. When set to *default* this field configuration issue type item applies to all issue types without a field configuration. */
    @Json(name = "issueTypeId")
    val issueTypeId: kotlin.String,
    /* The ID of the field configuration. */
    @Json(name = "fieldConfigurationId")
    val fieldConfigurationId: kotlin.String
) 



