/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.FoundGroup

import com.squareup.moshi.Json
/**
 * The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.
 * @param header Header text indicating the number of groups in the response and the total number of groups found in the search.
 * @param total The total number of groups found in the search.
 * @param groups 
 */

data class FoundGroups (
    /* Header text indicating the number of groups in the response and the total number of groups found in the search. */
    @Json(name = "header")
    val header: kotlin.String? = null,
    /* The total number of groups found in the search. */
    @Json(name = "total")
    val total: kotlin.Int? = null,
    @Json(name = "groups")
    val groups: kotlin.Array<FoundGroup>? = null
) 



