/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * An operand that is a function. See [Advanced searching - functions reference](https://confluence.atlassian.com/x/dwiiLQ) for more information about JQL functions.
 * @param function The name of the function.
 * @param arguments The list of function arguments.
 */

data class FunctionOperand (
    /* The name of the function. */
    @Json(name = "function")
    val function: kotlin.String,
    /* The list of function arguments. */
    @Json(name = "arguments")
    val arguments: kotlin.Array<kotlin.String>? = null
) 



