/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of functions that can be used in advanced searches.
 * @param value The function identifier.
 * @param displayName The display name of the function.
 * @param isList Whether the function can take a list of arguments.
 * @param types The data types returned by the function.
 */

data class FunctionReferenceData (
    /* The function identifier. */
    @Json(name = "value")
    val value: kotlin.String? = null,
    /* The display name of the function. */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,
    /* Whether the function can take a list of arguments. */
    @Json(name = "isList")
    val isList: FunctionReferenceData.IsList? = null,
    /* The data types returned by the function. */
    @Json(name = "types")
    val types: kotlin.Array<kotlin.String>? = null
) 


{
    /**
    * Whether the function can take a list of arguments.
    * Values: `true`,`false`
    */
    
    enum class IsList(val value: kotlin.String){
        @Json(name = "true") `true`("true"),
        @Json(name = "false") `false`("false");
    }
}

