/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.PagedListUserDetailsApplicationUser

import com.squareup.moshi.Json
/**
 * 
 * @param name The name of group.
 * @param self The URL for these group details.
 * @param users A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append `[start-index:end-index]` to the expand request. For example, to access the next 50 users, use`?expand=users[51:100]`.
 * @param expand Expand options that include additional group details in the response.
 */

data class Group (
    /* The name of group. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* The URL for these group details. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append `[start-index:end-index]` to the expand request. For example, to access the next 50 users, use`?expand=users[51:100]`. */
    @Json(name = "users")
    val users: PagedListUserDetailsApplicationUser? = null,
    /* Expand options that include additional group details in the response. */
    @Json(name = "expand")
    val expand: kotlin.String? = null
) 



