/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * A group label.
 * @param text The group label name.
 * @param title The title of the group label.
 * @param type The type of the group label.
 */

data class GroupLabel (
    /* The group label name. */
    @Json(name = "text")
    val text: kotlin.String? = null,
    /* The title of the group label. */
    @Json(name = "title")
    val title: kotlin.String? = null,
    /* The type of the group label. */
    @Json(name = "type")
    val type: GroupLabel.Type? = null
) 


{
    /**
    * The type of the group label.
    * Values: aDMIN,sINGLE,mULTIPLE
    */
    
    enum class Type(val value: kotlin.String){
        @Json(name = "ADMIN") aDMIN("ADMIN"),
        @Json(name = "SINGLE") sINGLE("SINGLE"),
        @Json(name = "MULTIPLE") mULTIPLE("MULTIPLE");
    }
}

