/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of user or system associated with a issue history metadata item.
 * @param id The ID of the user or system associated with a history record.
 * @param displayName The display name of the user or system associated with a history record.
 * @param displayNameKey The key of the display name of the user or system associated with a history record.
 * @param type The type of the user or system associated with a history record.
 * @param avatarUrl The URL to an avatar for the user or system associated with a history record.
 * @param url The URL of the user or system associated with a history record.
 */

data class HistoryMetadataParticipant (
    /* The ID of the user or system associated with a history record. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The display name of the user or system associated with a history record. */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,
    /* The key of the display name of the user or system associated with a history record. */
    @Json(name = "displayNameKey")
    val displayNameKey: kotlin.String? = null,
    /* The type of the user or system associated with a history record. */
    @Json(name = "type")
    val type: kotlin.String? = null,
    /* The URL to an avatar for the user or system associated with a history record. */
    @Json(name = "avatarUrl")
    val avatarUrl: kotlin.String? = null,
    /* The URL of the user or system associated with a history record. */
    @Json(name = "url")
    val url: kotlin.String? = null
) 



