/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * An icon.
 * @param url16x16 The URL of a 16x16 pixel icon.
 * @param title The title of the icon, for use as a tooltip on the icon.
 * @param link The URL of the tooltip, used only for a status icon.
 */

data class IconBean (
    /* The URL of a 16x16 pixel icon. */
    @Json(name = "url16x16")
    val url16x16: kotlin.String? = null,
    /* The title of the icon, for use as a tooltip on the icon. */
    @Json(name = "title")
    val title: kotlin.String? = null,
    /* The URL of the tooltip, used only for a status icon. */
    @Json(name = "link")
    val link: kotlin.String? = null
) 



