/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param included 
 * @param excluded 
 * @param actuallyIncluded 
 */

data class IncludedFields (
    @Json(name = "included")
    val included: kotlin.collections.Set<kotlin.String>? = null,
    @Json(name = "excluded")
    val excluded: kotlin.collections.Set<kotlin.String>? = null,
    @Json(name = "actuallyIncluded")
    val actuallyIncluded: kotlin.collections.Set<kotlin.String>? = null
) 



