/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.IssuesJqlMetaDataBean

import com.squareup.moshi.Json
/**
 * Meta data describing the `issues` context variable.
 * @param jql 
 */

data class IssuesMetaBean (
    @Json(name = "jql")
    val jql: IssuesJqlMetaDataBean? = null
) 



