/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of an issue type.
 * @param id The ID of the issue type.
 * @param name The name of the issue type.
 * @param avatarId The avatar of the issue type.
 */

data class IssueTypeInfo (
    /* The ID of the issue type. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The name of the issue type. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* The avatar of the issue type. */
    @Json(name = "avatarId")
    val avatarId: kotlin.Long? = null
) 



