/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Bulk operation filter details.
 * @param entityIds List of issues to perform the bulk delete operation on.
 * @param currentValue The value of properties to perform the bulk operation on.
 */

data class IssueFilterForBulkPropertyDelete (
    /* List of issues to perform the bulk delete operation on. */
    @Json(name = "entityIds")
    val entityIds: kotlin.collections.Set<kotlin.Long>? = null,
    /* The value of properties to perform the bulk operation on. */
    @Json(name = "currentValue")
    val currentValue: kotlin.Any? = null
) 



