/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details about the mapping between an issue type and a workflow.
 * @param issueType The ID of the issue type. Not required if updating the issue type-workflow mapping.
 * @param workflow The name of the workflow.
 * @param updateDraftIfNeeded Set to true to create or update the draft of a workflow scheme and update the mapping in the draft, when the workflow scheme cannot be edited. Defaults to `false`. Only applicable when updating the workflow-issue types mapping.
 */

data class IssueTypeWorkflowMapping (
    /* The ID of the issue type. Not required if updating the issue type-workflow mapping. */
    @Json(name = "issueType")
    val issueType: kotlin.String? = null,
    /* The name of the workflow. */
    @Json(name = "workflow")
    val workflow: kotlin.String? = null,
    /* Set to true to create or update the draft of a workflow scheme and update the mapping in the draft, when the workflow scheme cannot be edited. Defaults to `false`. Only applicable when updating the workflow-issue types mapping. */
    @Json(name = "updateDraftIfNeeded")
    val updateDraftIfNeeded: kotlin.Boolean? = null
) 



