/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.IssuePickerSuggestionsIssueType

import com.squareup.moshi.Json
/**
 * A list of issues suggested for use in auto-completion.
 * @param sections A list of issues for an issue type suggested for use in auto-completion.
 */

data class IssuePickerSuggestions (
    /* A list of issues for an issue type suggested for use in auto-completion. */
    @Json(name = "sections")
    val sections: kotlin.Array<IssuePickerSuggestionsIssueType>? = null
) 



