/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of an issue type scheme.
 * @param id The ID of the issue type scheme.
 * @param name The name of the issue type scheme.
 * @param description The description of the issue type scheme.
 * @param isDefault Whether the issue type scheme is the default.
 */

data class IssueTypeScheme (
    /* The ID of the issue type scheme. */
    @Json(name = "id")
    val id: kotlin.String,
    /* The name of the issue type scheme. */
    @Json(name = "name")
    val name: kotlin.String,
    /* The description of the issue type scheme. */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* Whether the issue type scheme is the default. */
    @Json(name = "isDefault")
    val isDefault: kotlin.Boolean? = null
) 



