/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.IssuesMetaBean
import org.openapitools.client.models.JiraExpressionsComplexityBean

import com.squareup.moshi.Json
/**
 * 
 * @param complexity Contains information about the expression complexity. For example, the number of steps it took to evaluate the expression.
 * @param issues Contains information about the `issues` variable in the context. For example, is the issues were loaded with JQL, information about the page will be included here.
 */

data class JiraExpressionEvaluationMetaDataBean (
    /* Contains information about the expression complexity. For example, the number of steps it took to evaluate the expression. */
    @Json(name = "complexity")
    val complexity: JiraExpressionsComplexityBean? = null,
    /* Contains information about the `issues` variable in the context. For example, is the issues were loaded with JQL, information about the page will be included here. */
    @Json(name = "issues")
    val issues: IssuesMetaBean? = null
) 



