/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.JiraExpressionAnalysis

import com.squareup.moshi.Json
/**
 * Details about the analysed Jira expression.
 * @param results The results of Jira expressions analysis.
 */

data class JiraExpressionsAnalysis (
    /* The results of Jira expressions analysis. */
    @Json(name = "results")
    val results: kotlin.Array<JiraExpressionAnalysis>
) 



