/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.IdOrKeyBean
import org.openapitools.client.models.JexpIssues

import com.squareup.moshi.Json
/**
 * 
 * @param issue The issue that is available under the `issue` variable when evaluating the expression.
 * @param issues The collection of issues that is available under the `issues` variable when evaluating the expression.
 * @param project The project that is available under the `project` variable when evaluating the expression.
 * @param sprint The ID of the sprint that is available under the `sprint` variable when evaluating the expression.
 * @param board The ID of the board that is available under the `board` variable when evaluating the expression.
 * @param serviceDesk The ID of the service desk that is available under the `serviceDesk` variable when evaluating the expression.
 * @param customerRequest The ID of the customer request that is available under the `customerRequest` variable when evaluating the expression. This is the same as the ID of the underlying Jira issue, but the customer request context variable will have a different type.
 */

data class JiraExpressionEvalContextBean (
    /* The issue that is available under the `issue` variable when evaluating the expression. */
    @Json(name = "issue")
    val issue: IdOrKeyBean? = null,
    /* The collection of issues that is available under the `issues` variable when evaluating the expression. */
    @Json(name = "issues")
    val issues: JexpIssues? = null,
    /* The project that is available under the `project` variable when evaluating the expression. */
    @Json(name = "project")
    val project: IdOrKeyBean? = null,
    /* The ID of the sprint that is available under the `sprint` variable when evaluating the expression. */
    @Json(name = "sprint")
    val sprint: kotlin.Long? = null,
    /* The ID of the board that is available under the `board` variable when evaluating the expression. */
    @Json(name = "board")
    val board: kotlin.Long? = null,
    /* The ID of the service desk that is available under the `serviceDesk` variable when evaluating the expression. */
    @Json(name = "serviceDesk")
    val serviceDesk: kotlin.Long? = null,
    /* The ID of the customer request that is available under the `customerRequest` variable when evaluating the expression. This is the same as the ID of the underlying Jira issue, but the customer request context variable will have a different type. */
    @Json(name = "customerRequest")
    val customerRequest: kotlin.Long? = null
) 



