/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * The JQL queries to be converted.
 * @param queryStrings A list of queries with user identifiers. Maximum of 100 queries.
 */

data class JQLPersonalDataMigrationRequest (
    /* A list of queries with user identifiers. Maximum of 100 queries. */
    @Json(name = "queryStrings")
    val queryStrings: kotlin.Array<kotlin.String>? = null
) 



