/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.JqlQueryClause
import org.openapitools.client.models.JqlQueryOrderByClause

import com.squareup.moshi.Json
/**
 * A parsed JQL query.
 * @param where 
 * @param orderBy 
 */

data class JqlQuery (
    @Json(name = "where")
    val where: JqlQueryClause? = null,
    @Json(name = "orderBy")
    val orderBy: JqlQueryOrderByClause? = null
) 



