/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.JqlQueryField

import com.squareup.moshi.Json
/**
 * An element of the order-by JQL clause.
 * @param field 
 * @param direction The direction in which to order the results.
 */

data class JqlQueryOrderByClauseElement (
    @Json(name = "field")
    val field: JqlQueryField? = null,
    /* The direction in which to order the results. */
    @Json(name = "direction")
    val direction: JqlQueryOrderByClauseElement.Direction? = null
) 


{
    /**
    * The direction in which to order the results.
    * Values: asc,desc
    */
    
    enum class Direction(val value: kotlin.String){
        @Json(name = "asc") asc("asc"),
        @Json(name = "desc") desc("desc");
    }
}

