/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.FunctionOperand
import org.openapitools.client.models.KeywordOperand
import org.openapitools.client.models.ValueOperand

import com.squareup.moshi.Json
/**
 * An operand that can be part of a list operand.
 * @param value The operand value.
 * @param function The name of the function.
 * @param keyword The keyword that is the operand value.
 * @param arguments The list of function arguments.
 */

data class JqlQueryUnitaryOperand (
    /* The operand value. */
    @Json(name = "value")
    val value: kotlin.String,
    /* The name of the function. */
    @Json(name = "function")
    val function: kotlin.String,
    /* The keyword that is the operand value. */
    @Json(name = "keyword")
    val keyword: JqlQueryUnitaryOperand.Keyword,
    /* The list of function arguments. */
    @Json(name = "arguments")
    val arguments: kotlin.Array<kotlin.String>? = null
) 


{
    /**
    * The keyword that is the operand value.
    * Values: empty
    */
    
    enum class Keyword(val value: kotlin.String){
        @Json(name = "empty") empty("empty");
    }
}

