/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * The schema of a field.
 * @param type The data type of the field.
 * @param items When the data type is an array, the name of the field items within the array.
 * @param system If the field is a system field, the name of the field.
 * @param custom If the field is a custom field, the URI of the field.
 * @param customId If the field is a custom field, the custom ID of the field.
 * @param configuration If the field is a custom field, the configuration of the field.
 */

data class JsonTypeBean (
    /* The data type of the field. */
    @Json(name = "type")
    val type: kotlin.String,
    /* When the data type is an array, the name of the field items within the array. */
    @Json(name = "items")
    val items: kotlin.String? = null,
    /* If the field is a system field, the name of the field. */
    @Json(name = "system")
    val system: kotlin.String? = null,
    /* If the field is a custom field, the URI of the field. */
    @Json(name = "custom")
    val custom: kotlin.String? = null,
    /* If the field is a custom field, the custom ID of the field. */
    @Json(name = "customId")
    val customId: kotlin.Long? = null,
    /* If the field is a custom field, the configuration of the field. */
    @Json(name = "configuration")
    val configuration: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null
) 



