/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.GroupName
import org.openapitools.client.models.RestrictedPermission

import com.squareup.moshi.Json
/**
 * Details of the group membership or permissions needed to receive the notification.
 * @param groups List of group memberships required to receive the notification.
 * @param permissions List of permissions required to receive the notification.
 */

data class NotificationRecipientsRestrictions (
    /* List of group memberships required to receive the notification. */
    @Json(name = "groups")
    val groups: kotlin.Array<GroupName>? = null,
    /* List of permissions required to receive the notification. */
    @Json(name = "permissions")
    val permissions: kotlin.Array<RestrictedPermission>? = null
) 



