/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.LinkGroup

import com.squareup.moshi.Json
/**
 * Details of the operations that can be performed on the issue.
 * @param linkGroups Details of the link groups defining issue operations.
 */

data class Operations (
    /* Details of the link groups defining issue operations. */
    @Json(name = "linkGroups")
    val linkGroups: kotlin.Array<LinkGroup>? = null
) 



