/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.PermissionGrant

import com.squareup.moshi.Json
/**
 * List of permission grants.
 * @param permissions Permission grants list.
 * @param expand Expand options that include additional permission grant details in the response.
 */

data class PermissionGrants (
    /* Permission grants list. */
    @Json(name = "permissions")
    val permissions: kotlin.Array<PermissionGrant>? = null,
    /* Expand options that include additional permission grant details in the response. */
    @Json(name = "expand")
    val expand: kotlin.String? = null
) 



