/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param key Project keys must be unique and start with an uppercase letter followed by one or more uppercase alphanumeric characters. The maximum length is 10 characters. Required when creating a project. Optional when updating a project.
 * @param name The name of the project. Required when creating a project. Optional when updating a project.
 * @param projectTypeKey The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes), which dictates the application-specific feature set. Required when creating a project. Not applicable for the Update project resource.
 * @param projectTemplateKey A prebuilt configuration for a project. The type of the `projectTemplateKey` must match with the type of the `projectTypeKey`. Required when creating a project. Not applicable for the Update project resource.
 * @param description A brief description of the project.
 * @param lead This parameter is deprecated because of privacy changes. Use `leadAccountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. The user name of the project lead. Either `lead` or `leadAccountId` must be set when creating a project. Optional when updating a project. Cannot be provided with `leadAccountId`.
 * @param leadAccountId The account ID of the project lead. Either `lead` or `leadAccountId` must be set when creating a project. Optional when updating a project. Cannot be provided with `lead`.
 * @param url A link to information about this project, such as project documentation
 * @param assigneeType The default assignee when creating issues for this project.
 * @param avatarId An integer value for the project's avatar.
 * @param issueSecurityScheme The ID of the issue security scheme for the project, which enables you to control who can and cannot view issues. Use the [Get issue security schemes](#api-rest-api-3-issuesecurityschemes-get) resource to get all issue security scheme IDs.
 * @param permissionScheme The ID of the permission scheme for the project. Use the [Get all permission schemes](#api-rest-api-3-permissionscheme-get) resource to see a list of all permission scheme IDs.
 * @param notificationScheme The ID of the notification scheme for the project. Use the [Get notification schemes](#api-rest-api-3-notificationscheme-get) resource to get a list of notification scheme IDs.
 * @param categoryId The ID of the project's category. A complete list of category IDs is found using the [Get all project categories](#api-rest-api-3-projectCategory-get) operation.
 */

data class ProjectInputBean (
    /* Project keys must be unique and start with an uppercase letter followed by one or more uppercase alphanumeric characters. The maximum length is 10 characters. Required when creating a project. Optional when updating a project. */
    @Json(name = "key")
    val key: kotlin.String? = null,
    /* The name of the project. Required when creating a project. Optional when updating a project. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes), which dictates the application-specific feature set. Required when creating a project. Not applicable for the Update project resource. */
    @Json(name = "projectTypeKey")
    val projectTypeKey: ProjectInputBean.ProjectTypeKey? = null,
    /* A prebuilt configuration for a project. The type of the `projectTemplateKey` must match with the type of the `projectTypeKey`. Required when creating a project. Not applicable for the Update project resource. */
    @Json(name = "projectTemplateKey")
    val projectTemplateKey: ProjectInputBean.ProjectTemplateKey? = null,
    /* A brief description of the project. */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* This parameter is deprecated because of privacy changes. Use `leadAccountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. The user name of the project lead. Either `lead` or `leadAccountId` must be set when creating a project. Optional when updating a project. Cannot be provided with `leadAccountId`. */
    @Json(name = "lead")
    val lead: kotlin.String? = null,
    /* The account ID of the project lead. Either `lead` or `leadAccountId` must be set when creating a project. Optional when updating a project. Cannot be provided with `lead`. */
    @Json(name = "leadAccountId")
    val leadAccountId: kotlin.String? = null,
    /* A link to information about this project, such as project documentation */
    @Json(name = "url")
    val url: kotlin.String? = null,
    /* The default assignee when creating issues for this project. */
    @Json(name = "assigneeType")
    val assigneeType: ProjectInputBean.AssigneeType? = null,
    /* An integer value for the project's avatar. */
    @Json(name = "avatarId")
    val avatarId: kotlin.Long? = null,
    /* The ID of the issue security scheme for the project, which enables you to control who can and cannot view issues. Use the [Get issue security schemes](#api-rest-api-3-issuesecurityschemes-get) resource to get all issue security scheme IDs. */
    @Json(name = "issueSecurityScheme")
    val issueSecurityScheme: kotlin.Long? = null,
    /* The ID of the permission scheme for the project. Use the [Get all permission schemes](#api-rest-api-3-permissionscheme-get) resource to see a list of all permission scheme IDs. */
    @Json(name = "permissionScheme")
    val permissionScheme: kotlin.Long? = null,
    /* The ID of the notification scheme for the project. Use the [Get notification schemes](#api-rest-api-3-notificationscheme-get) resource to get a list of notification scheme IDs. */
    @Json(name = "notificationScheme")
    val notificationScheme: kotlin.Long? = null,
    /* The ID of the project's category. A complete list of category IDs is found using the [Get all project categories](#api-rest-api-3-projectCategory-get) operation. */
    @Json(name = "categoryId")
    val categoryId: kotlin.Long? = null
) 


{
    /**
    * The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes), which dictates the application-specific feature set. Required when creating a project. Not applicable for the Update project resource.
    * Values: software,serviceDesk,business
    */
    
    enum class ProjectTypeKey(val value: kotlin.String){
        @Json(name = "software") software("software"),
        @Json(name = "service_desk") serviceDesk("service_desk"),
        @Json(name = "business") business("business");
    }
    /**
    * A prebuilt configuration for a project. The type of the `projectTemplateKey` must match with the type of the `projectTypeKey`. Required when creating a project. Not applicable for the Update project resource.
    * Values: pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusAgilityMinusKanban,pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusAgilityMinusScrum,pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusBasic,pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusKanbanMinusClassic,pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusScrumMinusClassic,atlassianPeriodServicedeskColonSimplifiedMinusItMinusServiceMinusDesk,atlassianPeriodServicedeskColonSimplifiedMinusInternalMinusServiceMinusDesk,atlassianPeriodServicedeskColonSimplifiedMinusExternalMinusServiceMinusDesk,atlassianPeriodServicedeskColonSimplifiedMinusHrMinusServiceMinusDesk,atlassianPeriodServicedeskColonSimplifiedMinusFacilitiesMinusServiceMinusDesk,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusContentMinusManagement,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusDocumentMinusApproval,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusLeadMinusTracking,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusProcessMinusControl,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusProcurement,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusProjectMinusManagement,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusRecruitment,atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusTaskMinus,atlassianPeriodJiraPeriodJiraMinusIncidentMinusManagementMinusPluginColonImMinusIncidentMinusManagement
    */
    
    enum class ProjectTemplateKey(val value: kotlin.String){
        @Json(name = "com.pyxis.greenhopper.jira:gh-simplified-agility-kanban") pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusAgilityMinusKanban("com.pyxis.greenhopper.jira:gh-simplified-agility-kanban"),
        @Json(name = "com.pyxis.greenhopper.jira:gh-simplified-agility-scrum") pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusAgilityMinusScrum("com.pyxis.greenhopper.jira:gh-simplified-agility-scrum"),
        @Json(name = "com.pyxis.greenhopper.jira:gh-simplified-basic") pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusBasic("com.pyxis.greenhopper.jira:gh-simplified-basic"),
        @Json(name = "com.pyxis.greenhopper.jira:gh-simplified-kanban-classic") pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusKanbanMinusClassic("com.pyxis.greenhopper.jira:gh-simplified-kanban-classic"),
        @Json(name = "com.pyxis.greenhopper.jira:gh-simplified-scrum-classic") pyxisPeriodGreenhopperPeriodJiraColonGhMinusSimplifiedMinusScrumMinusClassic("com.pyxis.greenhopper.jira:gh-simplified-scrum-classic"),
        @Json(name = "com.atlassian.servicedesk:simplified-it-service-desk") atlassianPeriodServicedeskColonSimplifiedMinusItMinusServiceMinusDesk("com.atlassian.servicedesk:simplified-it-service-desk"),
        @Json(name = "com.atlassian.servicedesk:simplified-internal-service-desk") atlassianPeriodServicedeskColonSimplifiedMinusInternalMinusServiceMinusDesk("com.atlassian.servicedesk:simplified-internal-service-desk"),
        @Json(name = "com.atlassian.servicedesk:simplified-external-service-desk") atlassianPeriodServicedeskColonSimplifiedMinusExternalMinusServiceMinusDesk("com.atlassian.servicedesk:simplified-external-service-desk"),
        @Json(name = "com.atlassian.servicedesk:simplified-hr-service-desk") atlassianPeriodServicedeskColonSimplifiedMinusHrMinusServiceMinusDesk("com.atlassian.servicedesk:simplified-hr-service-desk"),
        @Json(name = "com.atlassian.servicedesk:simplified-facilities-service-desk") atlassianPeriodServicedeskColonSimplifiedMinusFacilitiesMinusServiceMinusDesk("com.atlassian.servicedesk:simplified-facilities-service-desk"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-content-management") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusContentMinusManagement("com.atlassian.jira-core-project-templates:jira-core-simplified-content-management"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-document-approval") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusDocumentMinusApproval("com.atlassian.jira-core-project-templates:jira-core-simplified-document-approval"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-lead-tracking") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusLeadMinusTracking("com.atlassian.jira-core-project-templates:jira-core-simplified-lead-tracking"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-process-control") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusProcessMinusControl("com.atlassian.jira-core-project-templates:jira-core-simplified-process-control"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-procurement") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusProcurement("com.atlassian.jira-core-project-templates:jira-core-simplified-procurement"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-project-management") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusProjectMinusManagement("com.atlassian.jira-core-project-templates:jira-core-simplified-project-management"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-recruitment") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusRecruitment("com.atlassian.jira-core-project-templates:jira-core-simplified-recruitment"),
        @Json(name = "com.atlassian.jira-core-project-templates:jira-core-simplified-task-") atlassianPeriodJiraMinusCoreMinusProjectMinusTemplatesColonJiraMinusCoreMinusSimplifiedMinusTaskMinus("com.atlassian.jira-core-project-templates:jira-core-simplified-task-"),
        @Json(name = "com.atlassian.jira.jira-incident-management-plugin:im-incident-management") atlassianPeriodJiraPeriodJiraMinusIncidentMinusManagementMinusPluginColonImMinusIncidentMinusManagement("com.atlassian.jira.jira-incident-management-plugin:im-incident-management");
    }
    /**
    * The default assignee when creating issues for this project.
    * Values: pROJECTLEAD,uNASSIGNED
    */
    
    enum class AssigneeType(val value: kotlin.String){
        @Json(name = "PROJECT_LEAD") pROJECTLEAD("PROJECT_LEAD"),
        @Json(name = "UNASSIGNED") uNASSIGNED("UNASSIGNED");
    }
}

