/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id The ID of the project that the option's behavior applies to.
 * @param attributes Defines the behavior of the option in the project.If notSelectable is set, the option cannot be set as the field's value. This is useful for archiving an option that has previously been selected but shouldn't be used anymore.If defaultValue is set, the option is selected by default.
 */

data class ProjectScopeBean (
    /* The ID of the project that the option's behavior applies to. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* Defines the behavior of the option in the project.If notSelectable is set, the option cannot be set as the field's value. This is useful for archiving an option that has previously been selected but shouldn't be used anymore.If defaultValue is set, the option is selected by default. */
    @Json(name = "attributes")
    val attributes: kotlin.Array<ProjectScopeBean.Attributes>? = null
) 


{
    /**
    * Defines the behavior of the option in the project.If notSelectable is set, the option cannot be set as the field's value. This is useful for archiving an option that has previously been selected but shouldn't be used anymore.If defaultValue is set, the option is selected by default.
    * Values: notSelectable,defaultValue
    */
    
    enum class Attributes(val value: kotlin.String){
        @Json(name = "notSelectable") notSelectable("notSelectable"),
        @Json(name = "defaultValue") defaultValue("defaultValue");
    }
}

