/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Additional details about a project.
 * @param totalIssueCount Total issue count.
 * @param lastIssueUpdateTime The last issue update time.
 */

data class ProjectInsight (
    /* Total issue count. */
    @Json(name = "totalIssueCount")
    val totalIssueCount: kotlin.Long? = null,
    /* The last issue update time. */
    @Json(name = "lastIssueUpdateTime")
    val lastIssueUpdateTime: java.time.OffsetDateTime? = null
) 



