/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AvatarUrlsBean
import org.openapitools.client.models.UpdatedProjectCategory

import com.squareup.moshi.Json
/**
 * Details about a next-gen project.
 * @param self The URL of the project details.
 * @param id The ID of the project.
 * @param key The key of the project.
 * @param name The name of the project.
 * @param projectTypeKey The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.
 * @param simplified Whether or not the project is simplified.
 * @param avatarUrls The URLs of the project's avatars.
 * @param projectCategory The category the project belongs to.
 */

data class ProjectForScope (
    /* The URL of the project details. */
    @Json(name = "self")
    val self: kotlin.String? = null,
    /* The ID of the project. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The key of the project. */
    @Json(name = "key")
    val key: kotlin.String? = null,
    /* The name of the project. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project. */
    @Json(name = "projectTypeKey")
    val projectTypeKey: ProjectForScope.ProjectTypeKey? = null,
    /* Whether or not the project is simplified. */
    @Json(name = "simplified")
    val simplified: kotlin.Boolean? = null,
    /* The URLs of the project's avatars. */
    @Json(name = "avatarUrls")
    val avatarUrls: AvatarUrlsBean? = null,
    /* The category the project belongs to. */
    @Json(name = "projectCategory")
    val projectCategory: UpdatedProjectCategory? = null
) 


{
    /**
    * The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.
    * Values: software,serviceDesk,business
    */
    
    enum class ProjectTypeKey(val value: kotlin.String){
        @Json(name = "software") software("software"),
        @Json(name = "service_desk") serviceDesk("service_desk"),
        @Json(name = "business") business("business");
    }
}

