/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.PropertyKey

import com.squareup.moshi.Json
/**
 * List of property keys.
 * @param keys Property key details.
 */

data class PropertyKeys (
    /* Property key details. */
    @Json(name = "keys")
    val keys: kotlin.Array<PropertyKey>? = null
) 



