/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.SimpleErrorCollection

import com.squareup.moshi.Json
/**
 * 
 * @param modifiedIssues The IDs of the modified issues.
 * @param unmodifiedIssues The IDs of the unchanged issues, those issues where errors prevent modification.
 * @param errors A collection of errors related to unchanged issues. The collection size is limited, which means not all errors may be returned.
 */

data class RemoveOptionFromIssuesResult (
    /* The IDs of the modified issues. */
    @Json(name = "modifiedIssues")
    val modifiedIssues: kotlin.Array<kotlin.Long>? = null,
    /* The IDs of the unchanged issues, those issues where errors prevent modification. */
    @Json(name = "unmodifiedIssues")
    val unmodifiedIssues: kotlin.Array<kotlin.Long>? = null,
    /* A collection of errors related to unchanged issues. The collection size is limited, which means not all errors may be returned. */
    @Json(name = "errors")
    val errors: SimpleErrorCollection? = null
) 



