/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Icon
import org.openapitools.client.models.Status

import com.squareup.moshi.Json
/**
 * The linked item.
 * @param url The URL of the item.
 * @param title The title of the item.
 * @param summary The summary details of the item.
 * @param icon Details of the icon for the item. If no icon is defined, the default link icon is used in Jira.
 * @param status The status of the item.
 */

data class RemoteObject (
    /* The URL of the item. */
    @Json(name = "url")
    val url: kotlin.String,
    /* The title of the item. */
    @Json(name = "title")
    val title: kotlin.String,
    /* The summary details of the item. */
    @Json(name = "summary")
    val summary: kotlin.String? = null,
    /* Details of the icon for the item. If no icon is defined, the default link icon is used in Jira. */
    @Json(name = "icon")
    val icon: Icon? = null,
    /* The status of the item. */
    @Json(name = "status")
    val status: Status? = null
) 



