/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Application
import org.openapitools.client.models.RemoteObject

import com.squareup.moshi.Json
/**
 * Details of an issue remote link.
 * @param id The ID of the link.
 * @param self The URL of the link.
 * @param globalId The global ID of the link, such as the ID of the item on the remote system.
 * @param application Details of the remote application the linked item is in.
 * @param relationship Description of the relationship between the issue and the linked item.
 * @param `object` Details of the item linked to.
 */

data class RemoteIssueLink (
    /* The ID of the link. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The URL of the link. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* The global ID of the link, such as the ID of the item on the remote system. */
    @Json(name = "globalId")
    val globalId: kotlin.String? = null,
    /* Details of the remote application the linked item is in. */
    @Json(name = "application")
    val application: Application? = null,
    /* Description of the relationship between the issue and the linked item. */
    @Json(name = "relationship")
    val relationship: kotlin.String? = null,
    /* Details of the item linked to. */
    @Json(name = "object")
    val `object`: RemoteObject? = null
) 



