/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of an issue resolution.
 * @param self The URL of the issue resolution.
 * @param id The ID of the issue resolution.
 * @param description The description of the issue resolution.
 * @param name The name of the issue resolution.
 */

data class Resolution (
    /* The URL of the issue resolution. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* The ID of the issue resolution. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The description of the issue resolution. */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* The name of the issue resolution. */
    @Json(name = "name")
    val name: kotlin.String? = null
) 



