/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * A screen tab.
 * @param name The name of the screen tab. The maximum length is 255 characters.
 * @param id The ID of the screen tab.
 */

data class ScreenableTab (
    /* The name of the screen tab. The maximum length is 255 characters. */
    @Json(name = "name")
    val name: kotlin.String,
    /* The ID of the screen tab. */
    @Json(name = "id")
    val id: kotlin.Long? = null
) 



