/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ScreenTypeIDsBean

import com.squareup.moshi.Json
/**
 * A screen scheme.
 * @param id The ID of the screen scheme.
 * @param name The name of the screen scheme.
 * @param description The description of the screen scheme.
 * @param screens IDs of the screens for the associated screen types.
 */

data class ScreenScheme (
    /* The ID of the screen scheme. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The name of the screen scheme. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* The description of the screen scheme. */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* IDs of the screens for the associated screen types. */
    @Json(name = "screens")
    val screens: ScreenTypeIDsBean? = null
) 



