/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Details of an issue level security item.
 * @param self The URL of the issue level security item.
 * @param id The ID of the issue level security item.
 * @param description The description of the issue level security item.
 * @param name The name of the issue level security item.
 */

data class SecurityLevel (
    /* The URL of the issue level security item. */
    @Json(name = "self")
    val self: kotlin.String? = null,
    /* The ID of the issue level security item. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The description of the issue level security item. */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* The name of the issue level security item. */
    @Json(name = "name")
    val name: kotlin.String? = null
) 



