/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * A status category.
 * @param self The URL of the status category.
 * @param id The ID of the status category.
 * @param key The key of the status category.
 * @param colorName The name of the color used to represent the status category.
 * @param name The name of the status category.
 */

data class StatusCategory (
    /* The URL of the status category. */
    @Json(name = "self")
    val self: kotlin.String? = null,
    /* The ID of the status category. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The key of the status category. */
    @Json(name = "key")
    val key: kotlin.String? = null,
    /* The name of the color used to represent the status category. */
    @Json(name = "colorName")
    val colorName: kotlin.String? = null,
    /* The name of the status category. */
    @Json(name = "name")
    val name: kotlin.String? = null
) 



