/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.IssueTransition

import com.squareup.moshi.Json
/**
 * List of issue transitions.
 * @param expand Expand options that include additional transitions details in the response.
 * @param transitions List of issue transitions.
 */

data class Transitions (
    /* Expand options that include additional transitions details in the response. */
    @Json(name = "expand")
    val expand: kotlin.String? = null,
    /* List of issue transitions. */
    @Json(name = "transitions")
    val transitions: kotlin.Array<IssueTransition>? = null
) 



