/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param accountId The accountId of the user
 * @param email The email of the user
 */

data class UnrestrictedUserEmail (
    /* The accountId of the user */
    @Json(name = "accountId")
    val accountId: kotlin.String? = null,
    /* The email of the user */
    @Json(name = "email")
    val email: kotlin.String? = null
) 



