/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param emailAddress The email address for the user.
 * @param displayName The display name for the user.
 * @param self The URL of the user.
 * @param key The key for the user. When provided with `name`, overrides the value in `name` to set both `name` and `key`. This property is deprecated because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
 * @param name The username for the user. This property is deprecated because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
 * @param password A password for the user. If a password is not set, a random password is generated.
 * @param notification Sends the user an email confirmation that they have been added to Jira. Default is `false`.
 * @param applicationKeys Deprecated, do not use.
 */

data class UserWriteBean (
    /* The email address for the user. */
    @Json(name = "emailAddress")
    val emailAddress: kotlin.String,
    /* The display name for the user. */
    @Json(name = "displayName")
    val displayName: kotlin.String,
    /* The URL of the user. */
    @Json(name = "self")
    val self: kotlin.String? = null,
    /* The key for the user. When provided with `name`, overrides the value in `name` to set both `name` and `key`. This property is deprecated because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    @Json(name = "key")
    val key: kotlin.String? = null,
    /* The username for the user. This property is deprecated because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* A password for the user. If a password is not set, a random password is generated. */
    @Json(name = "password")
    val password: kotlin.String? = null,
    /* Sends the user an email confirmation that they have been added to Jira. Default is `false`. */
    @Json(name = "notification")
    val notification: kotlin.String? = null,
    /* Deprecated, do not use. */
    @Json(name = "applicationKeys")
    val applicationKeys: kotlin.Array<kotlin.String>? = null
) 



