/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.VersionUsageInCustomField

import com.squareup.moshi.Json
/**
 * Various counts of issues within a version.
 * @param self The URL of these count details.
 * @param issuesFixedCount Count of issues where the `fixVersion` is set to the version.
 * @param issuesAffectedCount Count of issues where the `affectedVersion` is set to the version.
 * @param issueCountWithCustomFieldsShowingVersion Count of issues where a version custom field is set to the version.
 * @param customFieldUsage List of custom fields using the version.
 */

data class VersionIssueCounts (
    /* The URL of these count details. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* Count of issues where the `fixVersion` is set to the version. */
    @Json(name = "issuesFixedCount")
    val issuesFixedCount: kotlin.Long? = null,
    /* Count of issues where the `affectedVersion` is set to the version. */
    @Json(name = "issuesAffectedCount")
    val issuesAffectedCount: kotlin.Long? = null,
    /* Count of issues where a version custom field is set to the version. */
    @Json(name = "issueCountWithCustomFieldsShowingVersion")
    val issueCountWithCustomFieldsShowingVersion: kotlin.Long? = null,
    /* List of custom fields using the version. */
    @Json(name = "customFieldUsage")
    val customFieldUsage: kotlin.Array<VersionUsageInCustomField>? = null
) 



