/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EntityProperty
import org.openapitools.client.models.UserDetails
import org.openapitools.client.models.Visibility

import com.squareup.moshi.Json
/**
 * Details of a worklog.
 * @param self The URL of the worklog item.
 * @param author Details of the user who created the worklog.
 * @param updateAuthor Details of the user who last updated the worklog.
 * @param comment A comment about the worklog in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/). Optional when creating or updating a worklog.
 * @param created The datetime on which the worklog was created.
 * @param updated The datetime on which the worklog was last updated.
 * @param visibility Details about any restrictions in the visibility of the worklog. Optional when creating or updating a worklog.
 * @param started The datetime on which the worklog effort was started. Required when creating a worklog. Optional when updating a worklog.
 * @param timeSpent The time spent working on the issue as days (\\#d), hours (\\#h), or minutes (\\#m or \\#). Required when creating a worklog if `timeSpentSeconds` isn't provided. Optional when updating a worklog. Cannot be provided if `timeSpentSecond` is provided.
 * @param timeSpentSeconds The time in seconds spent working on the issue. Required when creating a worklog if `timeSpent` isn't provided. Optional when updating a worklog. Cannot be provided if `timeSpent` is provided.
 * @param id The ID of the worklog record.
 * @param issueId The ID of the issue this worklog is for.
 * @param properties Details of properties for the worklog. Optional when creating or updating a worklog.
 */

data class Worklog (
    /* The URL of the worklog item. */
    @Json(name = "self")
    val self: java.net.URI? = null,
    /* Details of the user who created the worklog. */
    @Json(name = "author")
    val author: UserDetails? = null,
    /* Details of the user who last updated the worklog. */
    @Json(name = "updateAuthor")
    val updateAuthor: UserDetails? = null,
    /* A comment about the worklog in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/). Optional when creating or updating a worklog. */
    @Json(name = "comment")
    val comment: kotlin.Any? = null,
    /* The datetime on which the worklog was created. */
    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,
    /* The datetime on which the worklog was last updated. */
    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null,
    /* Details about any restrictions in the visibility of the worklog. Optional when creating or updating a worklog. */
    @Json(name = "visibility")
    val visibility: Visibility? = null,
    /* The datetime on which the worklog effort was started. Required when creating a worklog. Optional when updating a worklog. */
    @Json(name = "started")
    val started: java.time.OffsetDateTime? = null,
    /* The time spent working on the issue as days (\\#d), hours (\\#h), or minutes (\\#m or \\#). Required when creating a worklog if `timeSpentSeconds` isn't provided. Optional when updating a worklog. Cannot be provided if `timeSpentSecond` is provided. */
    @Json(name = "timeSpent")
    val timeSpent: kotlin.String? = null,
    /* The time in seconds spent working on the issue. Required when creating a worklog if `timeSpent` isn't provided. Optional when updating a worklog. Cannot be provided if `timeSpent` is provided. */
    @Json(name = "timeSpentSeconds")
    val timeSpentSeconds: kotlin.Long? = null,
    /* The ID of the worklog record. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The ID of the issue this worklog is for. */
    @Json(name = "issueId")
    val issueId: kotlin.String? = null,
    /* Details of properties for the worklog. Optional when creating or updating a worklog. */
    @Json(name = "properties")
    val properties: kotlin.Array<EntityProperty>? = null
) 



