/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.WorkflowTransitionRules

import com.squareup.moshi.Json
/**
 * Details about a workflow configuration update request.
 * @param workflows The list of workflows with transition rules to update.
 */

data class WorkflowTransitionRulesUpdate (
    /* The list of workflows with transition rules to update. */
    @Json(name = "workflows")
    val workflows: kotlin.Array<WorkflowTransitionRules>? = null
) 



