/**
* The Jira Cloud platform REST API
* Jira Cloud platform REST API documentation
*
* The version of the OpenAPI document: 1001.0.0-SNAPSHOT
* Contact: ecosystem@atlassian.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * Properties that identify a workflow.
 * @param name The name of the workflow.
 * @param draft Whether the workflow is in the draft state.
 */

data class WorkflowId (
    /* The name of the workflow. */
    @Json(name = "name")
    val name: kotlin.String,
    /* Whether the workflow is in the draft state. */
    @Json(name = "draft")
    val draft: kotlin.Boolean
) 



